### ISSUE TITLE
Deciding auth and db

### ISSUE THREAD

**Issue by husamettinarabaci** [Ubn-Jr/hirob-be-core#4]
We can use JWT for authentication, RBAC for Authorization, and PostgreSQL for DB.
Jwt is an effortless and more strong way for authentication. RBAC is role-based access control and it solves all our problems. Our data structure is predictable and not changeable so PostgreSQL fits our system.

**Comment by Sddilora** [comment]
These tools align with our system's requirements and objectives, and I believe they will contribute significantly to the security and reliability of our services. We can confidently opt for them.
